SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdvertGSEQuantity](
	[AdvertId] [int] NOT NULL,
	[GSETypeId] [int] NOT NULL,
	[QuantityId] [char](5) NOT NULL,
	[MetricValue] [float] NOT NULL,
 CONSTRAINT [PK_AdvertGSEQuantity] PRIMARY KEY CLUSTERED 
(
	[AdvertId] ASC,
	[GSETypeId] ASC,
	[QuantityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
