SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdvertGSEFeature](
	[AdvertGSEFeatureId] [int] NOT NULL,
	[AdvertId] [int] NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[Value] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_AdvertGSEFeature] PRIMARY KEY CLUSTERED 
(
	[AdvertGSEFeatureId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
