SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdvertStatus](
	[AdvertStatusId] [char](2) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[DisplayOrder] [int] NULL,
	[UserStatusYN] [bit] NULL,
 CONSTRAINT [PK_AdvertStatus] PRIMARY KEY CLUSTERED 
(
	[AdvertStatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
