SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdvertStatusHistory](
	[AdvertId] [int] NOT NULL,
	[DateTime] [datetime] NOT NULL,
	[AdvertStatusId] [char](2) NOT NULL,
 CONSTRAINT [PK_AdvertStatusHistory] PRIMARY KEY CLUSTERED 
(
	[AdvertId] ASC,
	[DateTime] ASC,
	[AdvertStatusId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
