SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GSEType](
	[GSETypeId] [int] NOT NULL,
	[DisplayOrder] [int] NULL,
	[Description] [nvarchar](50) NULL,
	[InUseYN] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[GSETypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
